
#line 3 "lex.fct_pddl.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer fct_pddl_create_buffer
#define yy_delete_buffer fct_pddl_delete_buffer
#define yy_flex_debug fct_pddl_flex_debug
#define yy_init_buffer fct_pddl_init_buffer
#define yy_flush_buffer fct_pddl_flush_buffer
#define yy_load_buffer_state fct_pddl_load_buffer_state
#define yy_switch_to_buffer fct_pddl_switch_to_buffer
#define yyin fct_pddlin
#define yyleng fct_pddlleng
#define yylex fct_pddllex
#define yylineno fct_pddllineno
#define yyout fct_pddlout
#define yyrestart fct_pddlrestart
#define yytext fct_pddltext
#define yywrap fct_pddlwrap
#define yyalloc fct_pddlalloc
#define yyrealloc fct_pddlrealloc
#define yyfree fct_pddlfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE fct_pddlrestart(fct_pddlin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int fct_pddlleng;

extern FILE *fct_pddlin, *fct_pddlout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up fct_pddltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up fct_pddltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via fct_pddlrestart()), so that the user can continue scanning by
	 * just pointing fct_pddlin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when fct_pddltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int fct_pddlleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow fct_pddlwrap()'s to do buffer switches
 * instead of setting up a fresh fct_pddlin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void fct_pddlrestart (FILE *input_file  );
void fct_pddl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE fct_pddl_create_buffer (FILE *file,int size  );
void fct_pddl_delete_buffer (YY_BUFFER_STATE b  );
void fct_pddl_flush_buffer (YY_BUFFER_STATE b  );
void fct_pddlpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void fct_pddlpop_buffer_state (void );

static void fct_pddlensure_buffer_stack (void );
static void fct_pddl_load_buffer_state (void );
static void fct_pddl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER fct_pddl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE fct_pddl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE fct_pddl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE fct_pddl_scan_bytes (yyconst char *bytes,int len  );

void *fct_pddlalloc (yy_size_t  );
void *fct_pddlrealloc (void *,yy_size_t  );
void fct_pddlfree (void *  );

#define yy_new_buffer fct_pddl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        fct_pddlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            fct_pddl_create_buffer(fct_pddlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        fct_pddlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            fct_pddl_create_buffer(fct_pddlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define fct_pddlwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *fct_pddlin = (FILE *) 0, *fct_pddlout = (FILE *) 0;

typedef int yy_state_type;

extern int fct_pddllineno;

int fct_pddllineno = 1;

extern char *fct_pddltext;
#define yytext_ptr fct_pddltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up fct_pddltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	fct_pddlleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[225] =
    {   0,
       16,   16,    0,    0,    0,    0,   54,   52,   47,   45,
        1,    2,   33,   32,    3,   34,   15,   52,   43,   36,
       37,   35,   52,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   53,   44,   46,   49,   48,
       50,   51,    0,    0,    0,   15,   15,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   43,   42,   39,   38,
       41,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   28,   40,   40,   40,    0,    0,    0,    0,    0,
        0,   15,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   41,   26,    0,   40,   40,   40,   40,   40,   40,

       31,   40,   40,   40,    0,    0,    0,    0,    0,    0,
       40,   40,   40,   40,   40,   40,   40,   40,   40,    0,
        0,   40,   40,   40,   40,   40,   40,   40,   40,   40,
        0,   44,    0,    0,    0,    0,    0,   40,   13,   14,
       40,   40,   40,   40,   40,   40,    0,    7,    0,    0,
       40,   40,   40,   27,   40,   40,   40,   40,   40,    0,
       48,    0,    0,    0,    0,   40,   40,   40,   40,   40,
       40,   40,    8,   30,   29,   40,   40,   40,   40,   40,
        0,    0,    0,    0,   24,   20,   17,   40,   40,   21,
       40,   40,   40,    9,   40,   40,    0,    5,    0,    0,

       12,   40,   40,   19,   18,   40,   40,   25,    0,    0,
       22,   40,   10,   40,    0,    0,   11,   23,    0,    4,
        0,    0,    6,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   41,   42,   43,   44,
       45,    1,   45,   46,   47,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   41,   42,
       43,   44,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,    1,    2
    } ;

static yyconst flex_int16_t yy_base[234] =
    {   0,
        0,    0,   45,   46,   49,   51,  286,  287,  287,  287,
       57,  287,  287,  287,  272,  287,   49,   63,  281,  266,
      287,  265,    0,   30,    0,  257,  238,  245,  246,   44,
      243,  239,  238,  246,  239,  226,  287,  225,  224,  287,
      223,  222,   64,   43,  234,   62,  253,    0,  231,  230,
      230,  238,  237,  239,  239,   53,  255,  287,  287,  287,
        0,    0,  234,  252,  230,  226,  216,  217,  209,  217,
      210,    0,  214,  208,  207,  240,  238,  201,  218,  217,
      230,  226,  206,  217,  208,  202,  195,  204,  195,  194,
      191,    0,    0,   71,  201,  190,  207,  195,  197,  196,

        0,  202,  182,  201,  217,  212,  179,  184,  180,  180,
      194,  182,  173,  185,  173,  185,  188,  179,  166,   96,
       99,  172,  165,  172,  159,  169,  168,  168,  178,  166,
      150,  287,  192,  170,  167,  152,  171,  162,    0,    0,
      150,  160,  165,  155,  165,  164,   84,  287,  100,  110,
      159,  144,  150,    0,  152,  151,  154,  138,  166,  129,
      287,  141,  134,  144,  149,  137,  142,  146,  128,  135,
      134,  125,    0,    0,    0,  119,  118,  129,  132,  120,
      135,  130,  119,  125,    0,    0,    0,  116,  129,    0,
      124,  127,  126,    0,  115,   94,   82,  287,   95,   98,

        0,   86,   81,    0,    0,   78,   76,  287,   75,   73,
        0,   63,    0,   69,   63,   59,    0,    0,   46,  287,
       37,   32,  287,  287,  123,  127,   62,  131,   50,  134,
      136,  140,  144
    } ;

static yyconst flex_int16_t yy_def[234] =
    {   0,
      224,    1,  225,  225,  226,  226,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  227,  228,  224,
      224,  224,  229,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  228,  224,  224,  224,
      231,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  224,  224,  224,  224,  224,
      224,  224,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  231,  230,  224,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  232,  224,  224,  224,  224,  224,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  224,
      224,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      224,  224,  233,  224,  224,  224,  224,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  224,  224,  224,  224,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  224,
      224,  224,  224,  224,  224,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      224,  224,  224,  224,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  224,  224,  224,  224,

      230,  230,  230,  230,  230,  230,  230,  224,  224,  224,
      230,  230,  230,  230,  224,  224,  230,  230,  224,  224,
      224,  224,  224,    0,  224,  224,  224,  224,  224,  224,
      224,  224,  224
    } ;

static yyconst flex_int16_t yy_nxt[335] =
    {   0,
        8,    8,    9,    8,   10,   11,   12,   13,   14,   15,
        8,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   25,   26,   27,   28,   25,   25,   29,   25,   25,
       25,   30,   31,   32,   33,   25,   25,   34,   35,   25,
       25,   25,   25,   25,    8,    8,    8,   37,   37,   38,
       38,   40,   61,   40,   41,   42,   41,   42,   43,   47,
       43,   46,   63,   69,   48,   43,   78,   43,   64,  223,
       44,   70,   47,   79,   46,  222,   90,   44,  221,   80,
       91,  120,  220,  121,   45,   49,  219,  147,   50,  148,
       51,   45,  218,   52,   53,  217,   54,   55,  216,  147,

       56,  148,  147,  147,  148,  148,  215,  214,  149,  120,
      213,  150,  149,  147,  212,  148,  211,  210,  209,  208,
      120,  207,  150,   36,   36,   36,   36,   39,   39,   39,
       39,   57,   57,   57,   57,   62,   62,   92,   92,   92,
      131,  131,  131,  131,  160,  160,  160,  160,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,   77,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,   76,  159,  158,  157,  156,

      155,  154,  153,  152,  151,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,
      130,  129,  128,  127,  126,  125,  124,  123,  122,  119,
      118,  117,  116,  115,  114,  113,  112,  111,   82,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   96,   95,   94,   93,   58,   89,   88,
       87,   86,   85,   84,   83,   82,   81,   77,   77,   77,
       76,   76,   75,   74,   73,   72,   71,   68,   67,   66,
       65,   60,   59,   58,   46,  224,    7,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224
    } ;

static yyconst flex_int16_t yy_chk[335] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    3,
        4,    5,  229,    6,    5,    5,    6,    6,   11,   17,
       11,   17,   24,   30,  227,   43,   44,   43,   24,  222,
       11,   30,   46,   44,   46,  221,   56,   43,  219,   44,
       56,   94,  216,   94,   11,   18,  215,  147,   18,  147,
       18,   43,  214,   18,   18,  212,   18,   18,  210,  120,

       18,  120,  121,  149,  121,  149,  209,  207,  120,  121,
      206,  121,  149,  150,  203,  150,  202,  200,  199,  197,
      150,  196,  150,  225,  225,  225,  225,  226,  226,  226,
      226,  228,  228,  228,  228,  230,  230,  231,  231,  231,
      232,  232,  232,  232,  233,  233,  233,  233,  195,  193,
      192,  191,  189,  188,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  160,  159,  158,  157,  156,  155,
      153,  152,  151,  146,  145,  144,  143,  142,  141,  138,
      137,  136,  135,  134,  133,  131,  130,  129,  128,  127,

      126,  125,  124,  123,  122,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  100,   99,   98,   97,   96,   95,   91,
       90,   89,   88,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   71,   70,
       69,   68,   67,   66,   65,   64,   63,   57,   55,   54,
       53,   52,   51,   50,   49,   47,   45,   42,   41,   39,
       38,   36,   35,   34,   33,   32,   31,   29,   28,   27,
       26,   22,   20,   19,   15,    7,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int fct_pddl_flex_debug;
int fct_pddl_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *fct_pddltext;
#line 1 "lex-fct_pddl.l"
/*********************************************************************
 * (C) Copyright 2000 Albert Ludwigs University Freiburg
 *     Institute of Computer Science
 *
 * All rights reserved. Use of this software is permitted for 
 * non-commercial research purposes, and it may be copied only 
 * for that use.  All copies must include this copyright message.
 * This software is made available AS IS, and neither the authors
 * nor the  Albert Ludwigs University Freiburg make any warranty
 * about the software or its performance. 
 *********************************************************************/
#line 20 "lex-fct_pddl.l"
#include "ff.h"
#include "parse.h"

#define fct_pddltext fct_pddltext

int gbracket_count = 0;


#line 641 "lex.fct_pddl.c"

#define INITIAL 0
#define COMMENT 1
#define OVERREAD 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int fct_pddllex_destroy (void );

int fct_pddlget_debug (void );

void fct_pddlset_debug (int debug_flag  );

YY_EXTRA_TYPE fct_pddlget_extra (void );

void fct_pddlset_extra (YY_EXTRA_TYPE user_defined  );

FILE *fct_pddlget_in (void );

void fct_pddlset_in  (FILE * in_str  );

FILE *fct_pddlget_out (void );

void fct_pddlset_out  (FILE * out_str  );

int fct_pddlget_leng (void );

char *fct_pddlget_text (void );

int fct_pddlget_lineno (void );

void fct_pddlset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int fct_pddlwrap (void );
#else
extern int fct_pddlwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( fct_pddltext, fct_pddlleng, 1, fct_pddlout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( fct_pddlin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( fct_pddlin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, fct_pddlin))==0 && ferror(fct_pddlin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(fct_pddlin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int fct_pddllex (void);

#define YY_DECL int fct_pddllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after fct_pddltext and fct_pddlleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 65 "lex-fct_pddl.l"


#line 828 "lex.fct_pddl.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! fct_pddlin )
			fct_pddlin = stdin;

		if ( ! fct_pddlout )
			fct_pddlout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			fct_pddlensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				fct_pddl_create_buffer(fct_pddlin,YY_BUF_SIZE );
		}

		fct_pddl_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of fct_pddltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 225 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 287 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 67 "lex-fct_pddl.l"
{ return(OPEN_PAREN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "lex-fct_pddl.l"
{  return(CLOSE_PAREN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 71 "lex-fct_pddl.l"
{return (MINUS_TOK);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 "lex-fct_pddl.l"
{  gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "lex-fct_pddl.l"
{  gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "lex-fct_pddl.l"
{  gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 7:
*yy_cp = (yy_hold_char); /* undo effects of setting up fct_pddltext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up fct_pddltext again */
YY_RULE_SETUP
#line 81 "lex-fct_pddl.l"
{return(TIMED_EL_TOK);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "lex-fct_pddl.l"
{  return(DEFINE_TOK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 "lex-fct_pddl.l"
{  return(PROBLEM_TOK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 87 "lex-fct_pddl.l"
{  return(SITUATION_TOK); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 89 "lex-fct_pddl.l"
{  return(BSITUATION_TOK); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "lex-fct_pddl.l"
{  return(OBJECTS_TOK); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "lex-fct_pddl.l"
{  return(GOAL_TOK); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 95 "lex-fct_pddl.l"
{  return(INIT_TOK); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "lex-fct_pddl.l"
{strupcase(fct_pddltext);strcpy(yylval.string, fct_pddltext);return (FLOATVAL);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 99 "lex-fct_pddl.l"
{strupcase(fct_pddltext);strcpy(yylval.string, fct_pddltext);return (INTVAL);} 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "lex-fct_pddl.l"
{  return(    METRIC_TOK); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "lex-fct_pddl.l"
{  return( MINIMIZE_TOK); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 107 "lex-fct_pddl.l"
{  return( MAXIMIZE_TOK); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "lex-fct_pddl.l"
{  return(    LENGTH_TOK); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 111 "lex-fct_pddl.l"
{  return(   SERIAL_TOK); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 113 "lex-fct_pddl.l"
{  return(  PARALLEL_TOK); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "lex-fct_pddl.l"
{  return(  TOTAL_TIME_TOK); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 117 "lex-fct_pddl.l"
{  return(BDOMAIN_TOK); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 119 "lex-fct_pddl.l"
{  gbracket_count = 1;
 BEGIN OVERREAD; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 122 "lex-fct_pddl.l"
{  return(AND_TOK); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 124 "lex-fct_pddl.l"
{  return(IMPLY_TOK); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 126 "lex-fct_pddl.l"
{  return(OR_TOK); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "lex-fct_pddl.l"
{  return(FORALL_TOK); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "lex-fct_pddl.l"
{  return(EXISTS_TOK); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 132 "lex-fct_pddl.l"
{  return(NOT_TOK); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "lex-fct_pddl.l"
{return (PLUS_TOK);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "lex-fct_pddl.l"
{return (MUL_TOK);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "lex-fct_pddl.l"
{return (DIV_TOK);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 140 "lex-fct_pddl.l"
{return (GREATER_TOK);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 142 "lex-fct_pddl.l"
{return (LESS_THAN_TOK);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 144 "lex-fct_pddl.l"
{  return(EQUAL_TOK); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 147 "lex-fct_pddl.l"
{ return(GREATER_OR_EQUAL_TOK);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 149 "lex-fct_pddl.l"
{ return(LESS_THAN_OR_EQUAL_TOK);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 152 "lex-fct_pddl.l"
{ strupcase( fct_pddltext );  
  strcpy(yylval.string, fct_pddltext ); return(NAME); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "lex-fct_pddl.l"
{strupcase( fct_pddltext );
 strcpy(yylval.string, fct_pddltext); return(VARIABLE); }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 159 "lex-fct_pddl.l"
{  lineno++; } 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 160 "lex-fct_pddl.l"
{  /* this will hold only in files that end with
		   a comment but no linefeed */ } 
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 163 "lex-fct_pddl.l"
{  lineno++; }  ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 165 "lex-fct_pddl.l"
{ BEGIN COMMENT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 167 "lex-fct_pddl.l"
{ BEGIN INITIAL;}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 169 "lex-fct_pddl.l"
{  lineno++; } 
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 171 "lex-fct_pddl.l"
{  lineno++; }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 173 "lex-fct_pddl.l"
{  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 175 "lex-fct_pddl.l"
{  gbracket_count++; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 177 "lex-fct_pddl.l"
{  gbracket_count--; 
  if (!gbracket_count) BEGIN INITIAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 180 "lex-fct_pddl.l"
{}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 181 "lex-fct_pddl.l"
ECHO;
	YY_BREAK
#line 1192 "lex.fct_pddl.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(OVERREAD):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed fct_pddlin at a new source and called
			 * fct_pddllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = fct_pddlin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( fct_pddlwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * fct_pddltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of fct_pddllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					fct_pddlrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			fct_pddlrestart(fct_pddlin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) fct_pddlrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 225 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 225 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 224);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up fct_pddltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					fct_pddlrestart(fct_pddlin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( fct_pddlwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve fct_pddltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void fct_pddlrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        fct_pddlensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            fct_pddl_create_buffer(fct_pddlin,YY_BUF_SIZE );
	}

	fct_pddl_init_buffer(YY_CURRENT_BUFFER,input_file );
	fct_pddl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void fct_pddl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		fct_pddlpop_buffer_state();
	 *		fct_pddlpush_buffer_state(new_buffer);
     */
	fct_pddlensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	fct_pddl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (fct_pddlwrap()) processing, but the only time this flag
	 * is looked at is after fct_pddlwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void fct_pddl_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	fct_pddlin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE fct_pddl_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) fct_pddlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in fct_pddl_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) fct_pddlalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in fct_pddl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	fct_pddl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with fct_pddl_create_buffer()
 * 
 */
    void fct_pddl_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		fct_pddlfree((void *) b->yy_ch_buf  );

	fct_pddlfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a fct_pddlrestart() or at EOF.
 */
    static void fct_pddl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	fct_pddl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then fct_pddl_init_buffer was _probably_
     * called from fct_pddlrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void fct_pddl_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		fct_pddl_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void fct_pddlpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	fct_pddlensure_buffer_stack();

	/* This block is copied from fct_pddl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from fct_pddl_switch_to_buffer. */
	fct_pddl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void fct_pddlpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	fct_pddl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		fct_pddl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void fct_pddlensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)fct_pddlalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in fct_pddlensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)fct_pddlrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in fct_pddlensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE fct_pddl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) fct_pddlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in fct_pddl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	fct_pddl_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to fct_pddllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       fct_pddl_scan_bytes() instead.
 */
YY_BUFFER_STATE fct_pddl_scan_string (yyconst char * yystr )
{
    
	return fct_pddl_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to fct_pddllex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE fct_pddl_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) fct_pddlalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in fct_pddl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = fct_pddl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in fct_pddl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up fct_pddltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		fct_pddltext[fct_pddlleng] = (yy_hold_char); \
		(yy_c_buf_p) = fct_pddltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		fct_pddlleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int fct_pddlget_lineno  (void)
{
        
    return fct_pddllineno;
}

/** Get the input stream.
 * 
 */
FILE *fct_pddlget_in  (void)
{
        return fct_pddlin;
}

/** Get the output stream.
 * 
 */
FILE *fct_pddlget_out  (void)
{
        return fct_pddlout;
}

/** Get the length of the current token.
 * 
 */
int fct_pddlget_leng  (void)
{
        return fct_pddlleng;
}

/** Get the current token.
 * 
 */

char *fct_pddlget_text  (void)
{
        return fct_pddltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void fct_pddlset_lineno (int  line_number )
{
    
    fct_pddllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see fct_pddl_switch_to_buffer
 */
void fct_pddlset_in (FILE *  in_str )
{
        fct_pddlin = in_str ;
}

void fct_pddlset_out (FILE *  out_str )
{
        fct_pddlout = out_str ;
}

int fct_pddlget_debug  (void)
{
        return fct_pddl_flex_debug;
}

void fct_pddlset_debug (int  bdebug )
{
        fct_pddl_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from fct_pddllex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    fct_pddlin = stdin;
    fct_pddlout = stdout;
#else
    fct_pddlin = (FILE *) 0;
    fct_pddlout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * fct_pddllex_init()
     */
    return 0;
}

/* fct_pddllex_destroy is for both reentrant and non-reentrant scanners. */
int fct_pddllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		fct_pddl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		fct_pddlpop_buffer_state();
	}

	/* Destroy the stack itself. */
	fct_pddlfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * fct_pddllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *fct_pddlalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *fct_pddlrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void fct_pddlfree (void * ptr )
{
	free( (char *) ptr );	/* see fct_pddlrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 181 "lex-fct_pddl.l"



